In [1]:
import sys
sys.path.append('/home/logic/proj/roughset')


from logic.roughset.roughset import Roughset as rs
import pandas as pd

df = pd.read_csv('./test2.csv')
df

    U    Age   LEMS Walk
0  x1  16-30     50  yes
1  x2  16-30      0   no
2  x3  31-45   1-25   no
3  x4  31-45   1-25  yes
4  x5  46-60  26-49   no
5  x6  16-30  26-49  yes
6  x7  46-60  26-49   no

In [2]:
df.index = df['U']
df.drop(columns=['U'],inplace=True)
df

      Age   LEMS Walk
U
x1  16-30     50  yes
x2  16-30      0   no
x3  31-45   1-25   no
x4  31-45   1-25  yes
x5  46-60  26-49   no
x6  16-30  26-49  yes
x7  46-60  26-49   no

In [3]:
X = df[df['Walk'].str.contains('y')]
X

      Age   LEMS Walk
U
x1  16-30     50  yes
x4  31-45   1-25  yes
x6  16-30  26-49  yes

In [4]:
A = ['Age','LEMS']
r = rs(df,A).init().set_X(X)

In [5]:
r

In [6]:
r.lower

[['x6'], ['x1']]

In [7]:
r.upper

[['x6'], ['x1'], ['x3', 'x4']]

In [10]:
upper_list = rs.flatten_list(r.upper)
upper_list

['x6', 'x1', 'x3', 'x4']

In [11]:
lower_list = rs.flatten_list(r.lower)
lower_list

['x6', 'x1']

In [15]:
r.bn

['x4', 'x3']

In [16]:
U = list(df.index)
U

['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7']

In [17]:
r.neg

['x7', 'x2', 'x5']

In [38]:
r.knowledge

[['x2'], ['x6'], ['x1'], ['x3', 'x4'], ['x5', 'x7']]

In [18]:
r.pos

[['x6'], ['x1']]