In [1]:
import pandas as pd ,numpy as np

In [2]:
df = pd.read_csv('./test2.csv')
df

    U    Age   LEMS Walk
0  x1  16-30     50  yes
1  x2  16-30      0   no
2  x3  31-45   1-25   no
3  x4  31-45   1-25  yes
4  x5  46-60  26-49   no
5  x6  16-30  26-49  yes
6  x7  46-60  26-49   no

In [19]:
g = df.groupby(by=['Age','Walk'])
g

In [21]:
k = g.count()
k

            U  LEMS
Age   Walk
16-30 no    1     1
      yes   2     2
31-45 no    1     1
      yes   1     1
46-60 no    2     2

In [26]:
k['P'] = k['LEMS'] / k['LEMS'].sum()
k['P']

Age    Walk
16-30  no      0.142857
       yes     0.285714
31-45  no      0.142857
       yes     0.142857
46-60  no      0.285714
Name: P, dtype: float64

In [27]:
k

            U  LEMS         P
Age   Walk
16-30 no    1     1  0.142857
      yes   2     2  0.285714
31-45 no    1     1  0.142857
      yes   1     1  0.142857
46-60 no    2     2  0.285714